### ISSUE TITLE
Using -- for long options

### ISSUE THREAD

**Issue by pimlottc** [waydabber/betterdisplaycli#1]
I'm very happy to see this new command line interface for BetterDisplay, it will certainly open a lot of doors for scripting and automation!

Currently the tool uses a single hyphen for long options, e.g. `betterdisplaycli get -brightness`.  Most tools these days use two for long options (e.g. `--brightness`) and keep single hyphens for single-letter options, either alone (e.g. `-h`) or in combination (e.g. `ls -latr`)

You might consider using the open source [Command Line Interface Guidelines](https://clig.dev/#arguments-and-flags) as a model for this (and other things).  Just wanted to offer this suggestion while the tool is new, before the syntax gets set in stone.

**Comment by pimlottc** [comment]
I realize macOS comes from a BSD lineage that historically preferred single-hyphen long arguments, but some of the built-in tools now use the newer style, such as `scutil` and `pkgutil`.

**Comment by waydabber** [comment]
Note: I'll update the app CLI wiki page + the app help to clarify this in the next app version + updated the readme to note this. :)

**Comment by waydabber** [comment]
https://github.com/waydabber/BetterDisplay/issues/2654
